version: "3.9"
services:
  db:
    platform: linux/amd64 # configuration for M1 macs
    image: mysql:8.0
    container_name: mysql_db
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: product_db
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - db

volumes:
  mysql_data:

# http://localhost:8080/ for phpMyAdmin
# https://medium.com/ucsc-isaca-student-group/how-to-run-mysql-with-docker-and-connect-with-phpmyadmin-ac23f2d50096#:~:text=Once%20the%20container%20is%20up,I%20have%20used%20%E2%80%9Cpass%E2%80%9D.

# create table product (id integer unique not null, name varchar(40), price float);
# insert into product values (1, 'Bombril', 7.9);
# insert into product values (2, 'Pasta', 3.0);